spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jpa:
    hibernate:
      # 테이블 자동 생성/수정
      ddl-auto: update
    # 실행되는 SQL을 콘솔에 출력
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect